spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/mailsystem1?serverTimezone=JST
    username: root
    password: 

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    org:
      springframework: WARN
    jp.co.openworker.mailsystem1.model.mapper: DEBUG